---
- hosts: all
  vars_files:
    - vars/main.yml
    - vars/vault

  roles:
    - role: dhcp
      tags: [ never, dhcp, bastion ]

    - role: dns
      tags: [ never, dns, bastion ]

    - role: haproxy
      tags: [ never, haproxy, bastion ]

    - role: pxe
      tags: [ never, pxe, bastion ]

    # go here to get your long lived access toekn https://cloud.redhat.com/openshift/token
    - role: ocp-prep
      tags: [ never, ocp-prep, bastion ]

    - role: startVMs
      tags: [ never, startVMs ]

    - role: stopBootstrap
      tags: [ never, stopBootstrap ]