---
# tasks file for dhcp
- name: Install DHCP
  become: true
  tags: install
  block:

    - name: Install packages for DHCP
      dnf:
        name:
          - dhcp-server
          - python3-netaddr
        state: present

    - name: setup firewall
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: "{{ firewall_zone }}"
      with_items: dhcp

    - name: Copy over configuration
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf

    - name: Starting services
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - dhcpd