---

- name: Install Load Balancer
  become: true
  tags: install
  block:

    - name: Install needed packages
      dnf:
        name:
          - haproxy
          - policycoreutils-python-utils
          - setools-console
        state: latest
        
    - name: setup firewall ports
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
        zone: internal
      with_items:
        - 80/tcp
        - 443/tcp
        - 6443/tcp
        - 22623/tcp
        - 9000/tcp

    - name: Write out haproxy config file
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: haproxy

    - name: SELinux role to allow HAProxy to access ports 6443 and 22623
      include_role:
        name: rhel-system-roles.selinux

    - name: Starting HAProxy service
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - haproxy